import axios from 'axios';
import { API_ENDPOINTS } from '@/api/endpoints';
import { ApiResponseHandler, CommonApiResponses, type ApiResponse } from '@/helpers';

// Helper function to get auth headers
const getAuthHeaders = () => {
  const token = localStorage.getItem('token');
  return {
    'Authorization': `Bearer ${token}`,
    'Content-Type': 'application/json'
  };
};

// Interface for auto-generated context response
export interface AutoGeneratedContext {
  business_type: string;
  photography_style: string;
  brand_personality: string;
  target_audience_details: string;
  visual_references: string | string[];  // String for new format, array for backward compatibility
}

// Interface for generate request
export interface GenerateAutoContextRequest {
  force_regenerate?: boolean;
}

// Auto Context service
export const autoContextService = {
  /**
   * Generate business context automatically using AI
   * @param force_regenerate - Force regeneration even if context already exists
   */
  generateContext: async (force_regenerate: boolean = false): Promise<ApiResponse<{
    message: string;
    context: AutoGeneratedContext;
    was_generated: boolean;
  }>> => {
    try {
      const payload: GenerateAutoContextRequest = {};
      if (force_regenerate) {
        payload.force_regenerate = true;
      }

      const response = await axios.post(
        API_ENDPOINTS.AUTO_CONTEXT.GENERATE,
        payload,
        {
          headers: getAuthHeaders()
        }
      );
      
      if (response?.data && response.data.success) {
        // Handle different response structures from backend
        let context: AutoGeneratedContext | undefined;
        let was_generated = true;
        const responseData = response.data;
        
        // Case 1: Newly generated context (from generated_context)
        if (responseData.generated_context) {
          context = responseData.generated_context;
          was_generated = true;
        }
        // Case 2: Existing context (from existing_context)
        else if (responseData.existing_context) {
          context = responseData.existing_context;
          was_generated = false;
        }
        // Case 3: Direct context field
        else if (responseData.context) {
          context = responseData.context;
          was_generated = responseData.was_generated !== false;
        }
        // Case 4: Data wrapper (from success_response helper)
        else if (responseData.data) {
          const data = responseData.data;
          if (data.generated_context) {
            context = data.generated_context;
            was_generated = true;
          } else if (data.existing_context) {
            context = data.existing_context;
            was_generated = false;
          } else if (data.context) {
            context = data.context;
            was_generated = data.was_generated !== false;
          }
        }
        
        if (!context) {
          return ApiResponseHandler.error(
            'INVALID_RESPONSE',
            'Respuesta inválida del servidor',
            'El servidor no devolvió un contexto válido'
          );
        }
        
        return ApiResponseHandler.success(
          {
            message: responseData.message || 'Contexto generado exitosamente',
            context: context,
            was_generated: was_generated
          },
          responseData.message || 'Contexto generado exitosamente'
        );
      }
      
      return ApiResponseHandler.error(
        'INVALID_RESPONSE',
        'Respuesta inválida del servidor',
        'El servidor no devolvió un contexto válido'
      );
    } catch (error: any) {
      if (error.response?.status === 401) {
        return CommonApiResponses.auth.sessionExpired();
      }
      
      if (error.response?.status === 404) {
        return ApiResponseHandler.error(
          'NOT_FOUND',
          'Información de empresa no encontrada',
          'Debes completar primero la información básica de tu empresa'
        );
      }

      if (error.response?.status === 400) {
        return ApiResponseHandler.error(
          'VALIDATION_ERROR',
          'Error de validación',
          error.response?.data?.error || 'No se pudo generar el contexto'
        );
      }
      
      if (error.response?.status === 500) {
        return ApiResponseHandler.error(
          'INTERNAL_ERROR',
          'Error del servidor',
          error.response?.data?.error || 'Ocurrió un error al generar el contexto con IA'
        );
      }
      
      return ApiResponseHandler.handleHttpError(error);
    }
  },

  /**
   * View current auto-generated context
   */
  viewContext: async (): Promise<ApiResponse<{
    has_context: boolean;
    context?: AutoGeneratedContext;
  }>> => {
    try {
      const response = await axios.get(
        API_ENDPOINTS.AUTO_CONTEXT.VIEW,
        {
          headers: getAuthHeaders()
        }
      );
      
      if (response?.data && response.data.success) {
        const responseData = response.data;
        return ApiResponseHandler.success(
          {
            has_context: responseData.has_context || false,
            context: responseData.context || responseData.data?.context
          },
          'Contexto obtenido exitosamente'
        );
      }
      
      return ApiResponseHandler.error(
        'INVALID_RESPONSE',
        'Respuesta inválida del servidor',
        'El servidor no devolvió información válida'
      );
    } catch (error: any) {
      if (error.response?.status === 401) {
        return CommonApiResponses.auth.sessionExpired();
      }
      
      if (error.response?.status === 404) {
        return ApiResponseHandler.error(
          'NOT_FOUND',
          'Información de empresa no encontrada',
          'No se ha configurado información de empresa'
        );
      }
      
      return ApiResponseHandler.handleHttpError(error);
    }
  }
};

export default autoContextService;

